# This file contains all the installation wide configuration which controls various settings in Chatwoot
# This is internal config and should not be modified by the user directly in database
# Chatwoot might override and modify these values during the upgrade process
# Configs which can be modified by the user are available in the dashboard under appropriate UI
#
# name: the name of the config referenced in the code
# value: the value of the config
# display_title: the title of the config displayed in the dashboard UI
# description: the description of the config displayed in the dashboard UI
# locked: if you don't specify locked attribute in yaml, the default value will be true,
#         which means the particular config will be locked and won't be available in `super_admin/installation_configs`
# premium: These values get overwritten unless the user is on a premium plan
# type: The type of the config. Default is text, select and boolean are also supported
# options: For select types, its required to have options for the select in the following pattern: "option_value":"Human readable option"

# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'PilotChat'
  display_title: 'Installation Name'
  description: 'The installation wide name that would be used in the dashboard, title etc.'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/logo_thumbnail.svg'
  display_title: 'Logo Thumbnail'
  description: 'The thumbnail that would be used for favicon (512px X 512px)'
- name: LOGO
  value: '/brand-assets/logo.svg'
  display_title: 'Logo'
  description: 'The logo that would be used on the dashboard, login page etc.'
- name: LOGO_DARK
  value: '/brand-assets/logo_dark.svg'
  display_title: 'Logo Dark Mode'
  description: 'The logo that would be used on the dashboard, login page etc. for dark mode'
- name: BRAND_URL
  value: ''
  display_title: 'Brand URL'
  description: 'The URL that would be used in emails under the section “Powered By”'
